#! /usr/bin/bash

#       col1 : col2 : col3 : col4 : col5 : col6 : col7
#R1 --> f1   : f2   : f3   : f4   : f5   : f6   : f7 
#R2 --> f1   : f2   : f3   : f4   : f5   : f6   : f7 
#R3 --> f1   : f2   : f3   : f4   : f5   : f6   : f7 
#R4 --> f1   : f2   : f3   : f4   : f5   : f6   : f7 

# awk 
# Field separator --> FS --> :
# Row separator --> (\n) (new line) --> RS
# Number of current row --> NR
# Number of fields --> NF 
# content of current line --> $0
# content of column --> $1,$2,$3 

# awk '{ print $0 }' /etc/passwd

# awk -F : '{print NR, $1}' /etc/passwd
<<COMMENT
awk 'BEGIN{
		FS=":"
		print "Start"
	}{
		
		print $1,$3,$3
		
	}END{
		print "END"
	}' /etc/passwd
 


awk 'BEGIN{
		FS=":"
		OFS="|"
		print "Start"
	}{
		
		if (NR == 46)
			print $1,$3
		
	}END{
		print "END"
	}' /etc/passwd


awk 'BEGIN{
		FS=":"
		OFS="|"
		print "Start"
	}{
		
		if (NR >=5 && NR <= 10)
			print NR,$1,$3
		
	}END{
		print "END"
	}' /etc/passwd



awk 'BEGIN{
		FS=":"
		sum=0
	}{
	
		sum+=$3
	}END{
		print "the sum of all id is " sum
	}' /etc/passwd


awk 'BEGIN{
		FS=":"
		max=0
		line=""
	}{
		if ( $3 > max ){
			max=$3
			line=$0
		}

			
	}END{
		print 
	}' /etc/passwd



awk 'BEGIN{
		FS=":"
		OFS=":"
	}{
		i=1
		line=""
		while (i<=NF){
			if ($i == "root"){
				$i="hamada"
				line=$0
			}
			
			i++
		}
		
		if (line != "")
			print line
			
	}END{

	}' /etc/passwd

COMMENT



































